version: '3.0' 

services:
 node:
  image: node:10
  volumes:
    - ".:/app"
  ports:
    - "5000:5000"
  links:
    - "database"
  working_dir: /app
  command: npm start
 database: 
  image: mongo
  ports:
  - "27017:27017"